name: Maps cat

env:
  ACTION_MAIL: "o.gruetzmann@gmail.com"
  ACTION_NAME: "ogruetzmann"
  ACTION_FILENAME_MAPS: "GRpluginMaps"
  ACTION_FILENAME_STANDS: "GRpluginStands"

on:
  push:
    paths: 
      - '$ACTION_FILENAME_MAPS/**'
      - '$ACTION_FILENAME_STANDS/**'

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
        
    MergeMaps:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
          - name: cat Maps
            run: cat $GITHUB_WORKSPACE/$ACTION_FILENAME_MAPS/*.txt >> $ACTION_FILENAME_MAPS.txt
    
    MergeStands:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
          - name: Merge Maps
            run: cat $GITHUB_WORKSPACE/$ACTION_FILENAME_STANDS/*.txt >> $ACTION_FILENAME_STANDS.txt
    
    Push:
        runs-on: ubuntu-latest
        needs: [MergeMaps, MergeStands]
        steps:
          - name: Push
            uses: ludeeus/action-push@0.0.1
